sudo: false
language: node_js
cache:
  npm: false
  directories:
    - .yarn/cache
matrix:
  include:
    - os: linux
      node_js: '12'
before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn=1.22.4-1
script:
  - 'yarn install'
  - 'yarn run build-prod'
