name: Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: .yarn/cache
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.4
    - run: yarn --version
    - run: yarn install
      env:
        FORCE_COLOR: 0
    - run: yarn run build-prod
      env:
        FORCE_COLOR: 0