name: Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # - uses: actions/cache@v1
    #   with:
    #     path: .yarn/cache
    #     key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
    #     restore-keys: |
    #       ${{ runner.os }}-yarn-
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install -g yarn
    - run: yarn --version
    - run: yarn set version 2.4.1
    - run: yarn install
    - run: yarn run build-prod
